/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author mayco
 */
public class telaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form telaTriangulo
     */
    public telaTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slA = new javax.swing.JSlider();
        slB = new javax.swing.JSlider();
        slC = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblForma = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(100, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 20, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        slA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        slA.setMaximum(20);
        slA.setValue(0);
        slA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slAStateChanged(evt);
            }
        });
        getContentPane().add(slA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 30));

        slB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        slB.setMaximum(20);
        slB.setValue(0);
        slB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBStateChanged(evt);
            }
        });
        getContentPane().add(slB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 30));

        slC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        slC.setMaximum(20);
        slC.setValue(0);
        slC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slCStateChanged(evt);
            }
        });
        getContentPane().add(slC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dfgdfg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        lblA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblA.setText("0");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 40, 30));

        lblB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblB.setText("0");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));

        lblC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblC.setText("0");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 30));

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 51, 255));
        lblTipo.setText("Tipo");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 680, -1));

        lblForma.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblForma.setForeground(new java.awt.Color(51, 153, 255));
        lblForma.setText("Forma um triângulo?");
        getContentPane().add(lblForma, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 680, -1));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jToggleButton1.setText("Testar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 210, 50));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int a = slA.getValue();
        int b = slB.getValue();
        int c = slC.getValue();
        
        if (a<b+c && b<a+c && c<a+b){
           lblForma.setText("Forma um Triângulo");
           if (a == b && b == c){
               lblTipo.setText("Equilátero");
           } else if (a!=b && b!=c && a!=c){
               lblTipo.setText("Escaleno");               
              } else {
                lblTipo.setText("Isócedes");
           }
        } else {
            lblForma.setText("Não forma um Triângulo");
        }
             
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void slAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slAStateChanged
        // TODO add your handling code here:
        lblA.setText(Integer.toString(slA.getValue()));
    }//GEN-LAST:event_slAStateChanged

    private void slBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBStateChanged
        // TODO add your handling code here:
        lblB.setText(Integer.toString(slB.getValue()));
    }//GEN-LAST:event_slBStateChanged

    private void slCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slCStateChanged
        // TODO add your handling code here:
        lblC.setText(Integer.toString(slC.getValue()));
    }//GEN-LAST:event_slCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblForma;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSlider slA;
    private javax.swing.JSlider slB;
    private javax.swing.JSlider slC;
    // End of variables declaration//GEN-END:variables
}
